name: Bloggy Blog
url: http://ki6bjv.com
description: Just a Blog
title: ki6bjv.com

permalink: /:title/
paginate: 3

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
